name: CI - Code Check & Security Scan

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    
    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: table
        output: 'trivy-portfolio-results.txt'
        severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

    - name: Trivy Summary
      run: |
        if [[ -s trivy-portfolio-results.txt ]]; then
          {
            echo "###Vulnerability Report"
            echo ""
            cat trivy-portfolio-results.txt
            echo "</details>"
          } >> $GITHUB-STEP_SUMMARY
        fi
    
